typography_spectrum: 0.9091675034724176
color:
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 0.0023004719987511635
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2698741036001593
analytics:
  google: UA-76145435-2
  facebook: null
  twitter: null
author:
  name: Jacob Wolf
  email: jacobawolf@gmail.com
name: Ohio Natural Health
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ohio Natural Health
purpose: []
