typography_spectrum: 0.15133474208414555
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.4770130009856075
  lightness: 0.44187093735672534
  saturation: 0.9393921191804111
  rhythmicContrast: 0.360936475219205
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5523607505019754
analytics:
  google: UA-76145435-2
  facebook: null
  twitter: null
author:
  name: Jacob Wolf
  email: jacobawolf@gmail.com
name: Ohio Natural Health
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ohio Natural Health
purpose: []
