layout_spectrum: 0.8415528326295316
typography_spectrum: 0.9435266382060945
color:
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 0.0023004719987511635
name: Ohio Natural Health
favicon: null
author:
  name: Jacob Wolf
  email: jacobawolf@gmail.com
title: Ohio Natural Health
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76145435-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
