typography_spectrum: 0.487664
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74218
analytics:
  google: UA-76145435-2
  facebook: null
  twitter: null
author:
  name: Jacob Wolf
  email: jacobawolf@gmail.com
name: Ohio Natural Health
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ohio Natural Health
purpose: []
