analytics: {}
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.139802
  lightness: 0.424342
  rhythmicContrast: 0.38987
  saturation: 0.771381
cta: {}
layout_spectrum: 0.47944
name: Ohio Natural Health
opengraph: {}
purpose: []
typography_spectrum: 0.487664
