name: Ohio Natural Health
favicon: null
layout_spectrum: 0.2657025051303208
typography_spectrum: 0.8163683847524226
title: Ohio Natural Health
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76145435-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.05243085324764252
  lightness: 0.5230663192924112
  saturation: 0.7146499673835933
  rhythmicContrast: 0.20020725904032588
purpose: []
